trigger: none

pr:
- master
- 8.x
- 10.x
    
pool:
    vmImage: ubuntu-20.04

jobs:
  - job: main
    steps:
      - script: |
          echo "BUILD_SOURCEVERSION = $BUILD_SOURCEVERSION"
          echo $BUILD_SOURCEVERSION
          echo $System.PullRequest.SourceCommitId
          echo $(System.PullRequest.SourceCommitId)
          echo $(SYSTEM.PULLREQUEST.SOURCECOMMITID)
          echo $SYSTEM.PULLREQUEST.SOURCECOMMITID
          echo $(SYSTEM_PULLREQUEST_SOURCECOMMITID)
          echo $SYSTEM_PULLREQUEST_SOURCECOMMITID
          echo "##vso[task.setvariable variable=PRNumber;isOutput=true]$(curl https://api.github.com/search/issues?q=sha:$BUILD_SOURCEVERSION | grep number | grep -o '[0-9]*')"
        displayName: Set output variables
        name: myEnv
  - job: variables_handler
    dependsOn: main
    variables:
      PRNumber: $[ dependencies.main.outputs['myEnv.PRNumber'] ]
    steps:
      - task: CmdLine@2
        displayName: Create artifact from variables
        inputs:
          script: |
            echo $PRNumber
            echo $(PRNumber)
            echo "##vso[task.setvariable variable=PRNumber;]$(PRNumber)" >  $(Build.ArtifactStagingDirectory)/pipeline.env
      # - task: PublishBuildArtifacts@1
      #   displayName: publish variables
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #     ArtifactName: 'variables'
      #     publishLocation: 'Container'
      - task: PublishPipelineArtifact@1
        displayName: publish variables
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'variables'
          publishLocation: 'pipeline'
      
      
