name: CI

# Run this workflow every time a pull request is opened against main
on:
  pull_request:
    branches: 
      - main
      - 10.x

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/lahirud0413/FromPocToScenarioTesting
            azure-pipeline-name: 'slahirucd7.GITHUB_ACTION_PIPELINE'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
